package com.ayoitshasya.matching.core.book;

import com.ayoitshasya.matching.core.domain.LimitOrder;
import com.ayoitshasya.matching.core.domain.Side;
import com.ayoitshasya.matching.core.domain.Trade;
import com.ayoitshasya.matching.core.exception.InvalidOrderException;
import com.ayoitshasya.matching.core.exception.OrderNotFoundException;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.OptionalLong;
import java.util.TreeMap;

/**
 * A single-symbol limit order book, matching incoming orders against resting ones under
 * price-time priority.
 *
 * <p>Bids and asks are each a {@link TreeMap} from price to {@link PriceLevel}: bids ordered
 * highest price first, asks lowest price first, so the best price on either side is always the
 * first entry. An incoming order matches while its limit price crosses the opposite side's best
 * price; the trade prints at the resting order's price, since the resting order was already
 * quoted at that price and the incoming order is the one crossing the spread to take it.
 *
 * <p>{@code ordersById} gives O(1) lookup for cancellation without a linear scan of price
 * levels. This class is not thread-safe; a later phase confines all mutation of one symbol's
 * book to a single writer thread rather than adding locking here.
 */
public final class OrderBook {

    private final String symbol;
    private final TreeMap<Long, PriceLevel> bids = new TreeMap<>(Comparator.reverseOrder());
    private final TreeMap<Long, PriceLevel> asks = new TreeMap<>(Comparator.naturalOrder());
    private final Map<Long, LimitOrder> ordersById = new HashMap<>();

    private long nextTradeId = 1;
    private long nextTradeSequence = 0;

    public OrderBook(String symbol) {
        if (symbol == null || symbol.isBlank()) {
            throw new InvalidOrderException("Order book symbol must not be blank");
        }
        this.symbol = symbol;
    }

    public String getSymbol() {
        return symbol;
    }

    /**
     * Submits a new limit order: matches it against the opposite side while its price crosses,
     * then rests any unfilled remainder in the book.
     *
     * @return the trades generated by this submission, in the order they occurred; empty if the
     *         order did not cross the book at all
     * @throws InvalidOrderException if the order's symbol does not match this book's, or an
     *                                order with the same ID is already resting in this book
     */
    public List<Trade> submit(LimitOrder order) {
        if (!symbol.equals(order.getSymbol())) {
            throw new InvalidOrderException(
                    "Order " + order.getId() + " has symbol " + order.getSymbol()
                            + " but this book trades " + symbol);
        }
        if (ordersById.containsKey(order.getId())) {
            throw new InvalidOrderException("An order with id " + order.getId() + " is already in the book");
        }

        List<Trade> trades = match(order);

        if (order.isActive() && order.getRemainingQuantity() > 0) {
            restInBook(order);
        }

        return trades;
    }

    /**
     * Cancels a resting order.
     *
     * @throws OrderNotFoundException if no order with this ID is resting in the book
     */
    public void cancel(long orderId) {
        LimitOrder order = ordersById.get(orderId);
        if (order == null) {
            throw new OrderNotFoundException(orderId);
        }

        order.cancel();
        sideOf(order.getSide()).get(order.getPrice()).removeOrder(orderId);
        removeLevelIfEmpty(sideOf(order.getSide()), order.getPrice());
        ordersById.remove(orderId);
    }

    public OptionalLong bestBidPrice() {
        return bids.isEmpty() ? OptionalLong.empty() : OptionalLong.of(bids.firstKey());
    }

    public OptionalLong bestAskPrice() {
        return asks.isEmpty() ? OptionalLong.empty() : OptionalLong.of(asks.firstKey());
    }

    /**
     * @return the best ask minus the best bid, or empty if either side of the book has no orders
     */
    public OptionalLong spread() {
        if (bids.isEmpty() || asks.isEmpty()) {
            return OptionalLong.empty();
        }
        return OptionalLong.of(asks.firstKey() - bids.firstKey());
    }

    /** @return up to {@code maxLevels} bid levels, best price first */
    public List<PriceLevelView> bidDepth(int maxLevels) {
        return depth(bids, maxLevels);
    }

    /** @return up to {@code maxLevels} ask levels, best price first */
    public List<PriceLevelView> askDepth(int maxLevels) {
        return depth(asks, maxLevels);
    }

    private List<Trade> match(LimitOrder incoming) {
        List<Trade> trades = new ArrayList<>();
        TreeMap<Long, PriceLevel> opposite = sideOf(oppositeOf(incoming.getSide()));

        while (incoming.getRemainingQuantity() > 0 && !opposite.isEmpty()) {
            Map.Entry<Long, PriceLevel> best = opposite.firstEntry();
            long bestPrice = best.getKey();
            if (!crosses(incoming, bestPrice)) {
                break;
            }

            PriceLevel level = best.getValue();
            Iterator<LimitOrder> restingOrders = level.ordersInFifoOrder();
            while (incoming.getRemainingQuantity() > 0 && restingOrders.hasNext()) {
                LimitOrder resting = restingOrders.next();
                long matchedQuantity = Math.min(incoming.getRemainingQuantity(), resting.getRemainingQuantity());

                incoming.fill(matchedQuantity);
                resting.fill(matchedQuantity);
                level.recordFill(matchedQuantity);
                trades.add(newTrade(incoming, resting, resting.getPrice(), matchedQuantity));

                if (!resting.isActive()) {
                    restingOrders.remove();
                    ordersById.remove(resting.getId());
                }
            }

            removeLevelIfEmpty(opposite, bestPrice);
        }

        return trades;
    }

    private boolean crosses(LimitOrder incoming, long oppositeBestPrice) {
        return incoming.getSide() == Side.BUY
                ? incoming.getPrice() >= oppositeBestPrice
                : incoming.getPrice() <= oppositeBestPrice;
    }

    private Trade newTrade(LimitOrder incoming, LimitOrder resting, long price, long quantity) {
        long buyOrderId = incoming.getSide() == Side.BUY ? incoming.getId() : resting.getId();
        long sellOrderId = incoming.getSide() == Side.BUY ? resting.getId() : incoming.getId();
        return new Trade(nextTradeId++, buyOrderId, sellOrderId, price, quantity, nextTradeSequence++);
    }

    private void restInBook(LimitOrder order) {
        PriceLevel level = sideOf(order.getSide())
                .computeIfAbsent(order.getPrice(), PriceLevel::new);
        level.addOrder(order);
        ordersById.put(order.getId(), order);
    }

    private void removeLevelIfEmpty(TreeMap<Long, PriceLevel> side, long price) {
        PriceLevel level = side.get(price);
        if (level != null && level.isEmpty()) {
            side.remove(price);
        }
    }

    private TreeMap<Long, PriceLevel> sideOf(Side side) {
        return side == Side.BUY ? bids : asks;
    }

    private static Side oppositeOf(Side side) {
        return side == Side.BUY ? Side.SELL : Side.BUY;
    }

    private static List<PriceLevelView> depth(TreeMap<Long, PriceLevel> side, int maxLevels) {
        if (maxLevels <= 0) {
            throw new IllegalArgumentException("maxLevels must be positive, got " + maxLevels);
        }

        List<PriceLevelView> levels = new ArrayList<>(Math.min(maxLevels, side.size()));
        for (PriceLevel level : side.values()) {
            if (levels.size() == maxLevels) {
                break;
            }
            levels.add(new PriceLevelView(level.getPrice(), level.getTotalQuantity(), level.getOrderCount()));
        }
        return levels;
    }
}
